[package]
name = "probman"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
dirs = "5.0"
toml = "0.8"
serde = {version = "1", features = ["derive"]}
reqwest = { version = "0.11", features = ["json"] }
uuid = { version = "1", features = ["serde", "v4"] }
tokio = { version = "1", features = ["full"] }
